language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: "BP8oV2E7jR8n/gMKGTneEdSfvy4ysUVP1CCYSJl9PMzZWvFbktXIiFasB2RFGnX7Q5b6gLttpWkJXAtI//cPvg7neEENmNLGvbcIJxMdXYtvJ9m+EM3/R3lo1Xt/mtkE5N/MbTGvsGYvuhHB9ZRk3qRjmIr42TjdIwGdbMZEHS4="
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - UNIT_TEST="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly
  - sudo apt-get update
  - sudo apt-get install openoffice.org python-genshi python-cairo python-openoffice python-lxml python-uno
  - sudo apt-get install zip
  - bzr branch lp:aeroolib ${HOME}/aeroolib
  - bzr branch lp:aeroo ${HOME}/aeroo
  - pushd ${HOME}/aeroolib/aeroolib; sudo python setup.py install; popd
 
script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
